### ISSUE TITLE
Download speed graph is blank

### ISSUE THREAD

**Issue by flatlinebb** [svenjacobs/sabdrop#23]
My speed graph is blank. Is there a setting in SABdrop or SABnzbd I missed? Using API auth to a server on my local network. I can see the files being downloaded and the speed control slider seems to be working.

Here is a screenshot:
[https://i.imgur.com/mg8IL1K.png](url)

EDIT:
Sorry, should have mentioned this:
Windows 10 Pro
Google Chrome Version 70.0.3538.110 (Official Build) (64-bit)

**Comment by svenjacobs** [comment]
Hm, that's weird. When you open the developer console of the extension, do you see any errors?

**Comment by flatlinebb** [comment]
Something like tyhis?

[image: image.png]
Please let me know if I should be looking elsewhere for errors.

**Comment by svenjacobs** [comment]
Unfortunately I can't see the attached image. Can you please it upload again?

**Comment by flatlinebb** [comment]
I uploaded it to imgur:
http://i.imgur.com/qogVjzS.jpg

**Comment by svenjacobs** [comment]
What version of SABnzbd are you using?

**Comment by flatlinebb** [comment]
Version  2.3.2

**Comment by svenjacobs** [comment]
Maybe something changed on SABnzbd's end? When this extension was written version **0.6.0** was the latest version of SABnzbd, so quite some time ago. Unfortunately I'm no longer a user of SABnzbd so I cannot reproduce this. But pull requests are greatly appreciated :)
